/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pdfbox.test

import java.io.File

import org.apache.fontbox.ttf.OTFParser
import org.apache.fontbox.ttf.TrueTypeFont
import org.apache.pdfbox.pdmodel.font.PDType0Font
import org.apache.pdfbox.pdmodel.PDDocument
import org.apache.pdfbox.pdmodel.PDPage
import org.apache.pdfbox.pdmodel.PDPageContentStream

fun createPdf(text: String, fileName: String) {
    val document = PDDocument()
    val page = PDPage()
    val otf = OTFParser(false, true).parse(
        File(String.format("%s/src/main/resources/%s", System.getProperty("user.dir"), "NotoSansJP-Regular.otf"))
    )
    val font = PDType0Font.load(document, otf as TrueTypeFont, false)
    document.addPage( page )
    
    val contentStream = PDPageContentStream(document, page)
    contentStream.beginText()
    contentStream.setFont( font, 12.0f )
    contentStream.moveTextPositionByAmount( 100.0f, 700.0f )
    contentStream.drawString( text )
    contentStream.endText()
    contentStream.close();

    document.save(fileName);
    document.close();
}

fun main(args: Array<String>) {
    val settings = mapOf(
        "garbled.pdf" to "注文書兼注文請書Webページのボタン⽤GIF画像編集"
    )
    for ((k, v) in settings) {
        createPdf(v, k)
    }
}
